services:
  rpi-mon:
    image: ghcr.io/spindev/rpi-mon:latest
    # If you encounter platform issues on Raspberry Pi, you can:
    # 1. Uncomment the next line to force ARM64 platform selection
    # platform: linux/arm64
    # 2. Or build locally: docker-compose build
    # build: .
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      # Mount system information directories for reading hardware info
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc:/host/etc:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    privileged: true  # Needed for full system access